[package]
name = "growtopia_item_decode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
clap = "2.33.3"